version: '2.2'

services:

  master:
    image: jmeteracrrepo.azurecr.io/jmeter:jmeter5.3Azmastergocd
    container_name: jm_master
    hostname: master
    # volumes:
    #   - ./test/:/jmeter/apache-jmeter-5.4.3/test/
    #command : "COPY $PWD/Pipeline_SampleScript.jmx /jmeter/apache-jmeter-5.4.3/Pipeline_SampleScript.jmx"
    command : "/bin/bash"
    #tty: true
    networks:
      - dist
  
  slave:
    image: jmeteracrrepo.azurecr.io/jmeter:jmeter5.3Azslavegocd
    depends_on:
      - master
    # volumes:
    #   - ./test/:/jmeter/apache-jmeter-5.4.3/test
    #command : "COPY $PWD/Pipeline_SampleScript.jmx /jmeter/apache-jmeter-5.4.3/Pipeline_SampleScript.jmx"
    #tty: true
    networks:
      - dist
  
networks:
  dist:
    driver: bridge